# Generated by Django 4.2.7 on 2024-01-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day4app', '0003_course_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='choice',
            field=models.CharField(choices=[('Theory', 'Theory'), ('Lab', 'Lab'), ('Project', 'Project')], default='Theory', max_length=20),
        ),
    ]
