# Generated by Django 4.2.7 on 2024-02-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day4app', '0004_alter_course_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='choice',
            field=models.CharField(choices=[('Theory', 'T'), ('Lab', 'L'), ('Project', 'P')], default='Theory', max_length=20),
        ),
    ]
