# Generated by Django 4.2.7 on 2024-01-30 09:29

import day4app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day4app', '0002_alter_course_att_full_marks_alter_course_credit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(default='THEORY', max_length=40, verbose_name=day4app.models.CourseType),
        ),
    ]
