# Generated by Django 4.2.7 on 2024-01-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day4app', '0004_alter_course_course_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('Theory', 'Theory'), ('Laboratory', 'Laboratory'), ('Project', 'Project')], default='Theory', max_length=40),
        ),
    ]
