# Generated by Django 4.2.8 on 2024-02-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day4app', '0005_alter_course_course_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stu_id', models.IntegerField()),
                ('name', models.CharField(max_length=40)),
                ('stu_exam_roll', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
