# Generated by Django 4.2.8 on 2024-02-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day4app', '0006_student_delete_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=10)),
                ('course_name', models.CharField(max_length=40)),
                ('course_type', models.CharField(choices=[('Theory', 'Theory'), ('Laboratory', 'Laboratory'), ('Project', 'Project')], default='Theory', max_length=40)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=4)),
                ('tutorial_full_marks', models.DecimalField(decimal_places=2, max_digits=4)),
                ('att_full_marks', models.DecimalField(decimal_places=2, max_digits=4)),
                ('final_full_marks', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
