# Generated by Django 5.0.2 on 2024-02-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day4app', '0008_student_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='student_photos/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Stu_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(blank=True, to='day4app.course'),
        ),
    ]
