# Generated by Django 4.2.7 on 2024-04-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day4app', '0010_remove_student_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=20)),
                ('courses', models.TextField()),
            ],
        ),
    ]
