# Generated by Django 4.2.7 on 2024-04-04 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day4app', '0012_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=100)),
                ('session', models.CharField(max_length=100)),
                ('committee_chief', models.CharField(max_length=100)),
                ('member_1', models.CharField(max_length=100)),
                ('member_2', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='rate',
            name='name',
            field=models.CharField(choices=[('Making Question Paper', 'প্রশ্নপত্র প্রণয়ন'), ('Evaluating Answer Scripts', 'উত্তরপত্র মূল্যায়ন'), ('Lab Exam', 'ব্যবহারিক পরীক্ষা'), ('Viva Exam', 'মৌখিক পরীক্ষা'), ('Question Moderation', 'প্রশ্নপত্র মডারেশন'), ('Stencil', 'স্টেনসিল কাটা'), ('Translation', 'অনুবাদ'), ('Thesis/Project/Report Evaluation', 'থিসিস/প্রজেক্ট/রিপোর্ট মূল্যায়ন'), ('Practice', 'অনুশীলনী'), ('Tabulation', 'টেবুলেশন'), ('Exam Committee Chief_s Remuneration', 'কমিটির সভাপতির পারিতোষিক'), ('Remuneration of Supervisor(M.Phil/PhD)', 'তত্ত্বাবধায়ক সম্মানী(এম. ফিল/ পিএইচ.ডি')], max_length=100),
        ),
    ]
