# Generated by Django 4.2.7 on 2024-05-16 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('day4app', '0016_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='yourmodel',
            name='image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='day4app.facultymember'),
        ),
    ]
