# Generated by Django 4.2.7 on 2024-05-16 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('day4app', '0017_yourmodel_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yourmodel',
            old_name='image',
            new_name='faculty_member',
        ),
    ]
